---
- content: |
    Praxiserfahrung aus echten Projekten
- content: |
    Vendor-neutral / Community OpenStack
- content: |
    Kursunterlagen öffentlich einsehbar, Sie wissen vor der Buchung was Sie erwartet.
